const data = [
    {
        month:"Jan",
        sales:"0.1",
        profits:"0.07",
        growth:"0.05"
    },
    {
        month:"Feb",
        sales:"0.1",
        profits:"0.08",
        growth:"0.07"
    },
    {
        month:"Mar",
        sales:"0.11",
        profits:"0.05",
        growth:"0.03"
    },
    {
        month:"Apr",
        sales:"0.09",
        profits:"0.06",
        growth:"0.08"
    },
    {
        month:"May",
        sales:"0.13",
        profits:"0.07",
        growth:"0.05"
    },
    {
        month:"June",
        sales:"0.11",
        profits:"0.05",
        growth:"0.03"
    },
    {
        month:"July",
        sales:"0.1",
        profits:"0.04",
        growth:"0.02"
    },
    {
        month:"Aug",
        sales:"0.13",
        profits:"0.07",
        growth:"0.05"
    },
    {
        month:"Sep",
        sales:"0.11",
        profits:"0.05",
        growth:"0.02"
    },
    {
        month:"Oct",
        sales:"0.13",
        profits:"0.08",
        growth:"0.03"
    },
    {
        month:"Nov",
        sales:"0.1",
        profits:"0.03",
        growth:"0.01"
    },
    {
        month:"Dec",
        sales:"0.15",
        profits:"0.07",
        growth:"0.04"
    },
]


export default data